name: influxdb
version: '1.7.1.1'
synopsis: Haskell client library for InfluxDB
description: ! '@influxdb@ is a Haskell client library for InfluxDB.


  See "Database.InfluxDB" for a quick start guide.'
category: Database
author: Mitsutoshi Aoe
maintainer: Mitsutoshi Aoe <me@maoe.name>
copyright: Copyright (C) 2014-2019 Mitsutoshi Aoe
license: BSD3
github: maoe/influxdb-haskell.git
extra-source-files:
- README.md
- CHANGELOG.md
library:
  source-dirs: src
  other-extensions:
  - BangPatterns
  - CPP
  - DataKinds
  - DeriveDataTypeable
  - DeriveGeneric
  - ExistentialQuantification
  - FlexibleInstances
  - FunctionalDependencies
  - GADTs
  - GeneralizedNewtypeDeriving
  - KindSignatures
  - LambdaCase
  - MultiParamTypeClasses
  - NamedFieldPuns
  - OverloadedStrings
  - RecordWildCards
  - ScopedTypeVariables
  - StandaloneDeriving
  - TemplateHaskell
  - ViewPatterns
  ghc-options: -Wall
  exposed-modules:
  - Database.InfluxDB
  - Database.InfluxDB.Format
  - Database.InfluxDB.JSON
  - Database.InfluxDB.Line
  - Database.InfluxDB.Manage
  - Database.InfluxDB.Ping
  - Database.InfluxDB.Query
  - Database.InfluxDB.Types
  - Database.InfluxDB.Write
  - Database.InfluxDB.Write.UDP
  dependencies:
  - base >=4.9 && <4.14
  - aeson >=0.7 && <1.5
  - attoparsec <0.14
  - bytestring >=0.10 && <0.11
  - clock >=0.7 && <0.9
  - containers >=0.5 && <0.7
  - foldl <1.5
  - http-client >=0.5 && <0.7
  - http-types >=0.8.6 && <0.13
  - lens >=4.9 && <4.19
  - network >=2.6 && <3.2
  - optional-args >=1.0 && <1.1
  - scientific >=0.3.3 && <0.4
  - tagged >=0.1 && <0.9
  - text <1.3
  - time >=1.5 && <1.10
  - unordered-containers <0.3
  - vector >=0.10 && <0.13
executables:
  influx-write-udp:
    main: write-udp.hs
    source-dirs: examples
    ghc-options: -Wall
    dependencies:
    - base
    - containers
    - influxdb
    - lens
    - network
    - time
    when:
    - condition: ! '!(flag(examples))'
      buildable: false
  influx-random-points:
    main: random-points.hs
    source-dirs: examples
    ghc-options: -Wall
    dependencies:
    - aeson
    - base
    - bytestring
    - containers
    - foldl >=1.1.3
    - http-client
    - influxdb
    - lens
    - mwc-random
    - optional-args
    - text
    - time
    - vector
    when:
    - condition: ! '!(flag(examples))'
      buildable: false
tests:
  doctests:
    main: doctests.hs
    source-dirs: tests
    ghc-options:
    - -Wall
    - -threaded
    dependencies:
    - base
    - doctest >=0.11.3 && <0.17
    - influxdb
    - template-haskell
  regressions:
    main: regressions.hs
    source-dirs: tests
    ghc-options:
    - -Wall
    - -threaded
    dependencies:
    - base
    - containers
    - influxdb
    - tasty
    - tasty-hunit
    - time
    - raw-strings-qq >=1.1 && <1.2
flags:
  examples:
    description: Build examples
    manual: true
    default: false
tested-with: ghc ==8.0.2 ghc ==8.2.2 ghc ==8.4.4 ghc ==8.6.5 ghc ==8.8.1
